Hydroflame522/StateFarmClient

- StateFarmClient.js
fixed bug where !extract("prediction") was not working or when prediction is not selected by the user, y vals were off
> fixed !prediction bug -urgent- for nonselected prediction to work

- StateFarmClient.js
will try to merge this with current changes, to prevent overwriting in merge conflicts if any
antisneak set default to 1.8, works like this:
user is targeting someone far away
enemy player sneaks up behind them
--> inside a radius of 1.8 BOOM! MAGDUMP on them, then switch to pistol and magdump, then reload and continue think of it like a tripwire where you are aiming on a target, say, and someone trips within your tripwire's radius now you are firing on them
> Better AntiSneak, autofires on detection of sneaking up player

- StateFarmClient.js
OP, works when aimbot enabled
user looking at far away target
player sneaks up
within radius set by user ? MAGDUMP : keep targeting
> AntiSneakAutoFire

- StateFarmClient.js
1. adds handler for killing yourself
2. new cheataccuse message
3. code cleanup
> improve interceptdeath

- StateFarmClient.js
statefarm now works on all crackedshell clients.
https://github.com/VillainsRule/CrackedShell
https://shell.onlypuppy7.online
> pre49 - update for crackedshell!

- StateFarmClient.js
ShellPrint generates Shell Shockers accounts.
To prevent BWD from finding out how we do this exactly, we use a key system.
You can unlock keys in my [Discord Server](discord.gg/XAyZ6ndEd4).
> add shellprint

- StateFarmClient.js
Auto Start (Hidden)
Notifs
Notif sound
> Update to chat w/ new settings

- StateFarmClient.js
this fixes various eslint issues, which removes the red `x` and yellow `!` lining parts of the script.
this also bumps to pre3, to account for @enbyte's previous changes (formatting).
this also fixes loadup console spam involving `USERDATA is not defined`. there was an issue with `ss` object initialization.
> fix eslint issues + more

- StateFarmClient.js
this commit implements a new version/concept of shellprint using the /v2 api path.
this also adds the GM_openInTab grant, which can be used to bypass window open blocks.
this also adds values to globalSS as well as fixes some console errors on loadup.
> shellprint v2, gm_openInTab, & more

- StateFarmClient.js
i meant to write shellprint oopsies :/
yea this just rewrites the UI
> pre8 - redo shellprint* UI (better descriptors & errors msgs)

- StateFarmClient.js
this requires you to have proper instance handling added in [this commit](https://github.com/xynacore/CrackedShell/commit/e440899d7c20e14b2e3f01b1fe655c132690f808).
> pre34: botting on select crackedshell versions

- StateFarmClient.js
> pre 41 - add Hide on startup

- StateFarmClient.js
> zowwy zwert :3

- StateFarmClient.js
contains some of my test modules you might not want but go cry about it
> Sex branch merge

- StateFarmClient.js
targets who are not in the minangle anymore are now deselected
> Silent MA deselect

- README.md
there hasnt been an update for a long time, has there?
> update Readme for version 3.4.1-pre52

- StateFarmClient.js
> pre54: fix minor spelling mistake

- StateFarmClient.js
now uses a TransformNode instead of an empty mesh
TN's are like empty coordinate systems, so exactly what we want here. ESP usually uses the object's meshes, but because prediction doesn't have a mesh, I used to create an empty one, to have a relative position. TN's do the same just without the mesh stuff we don't need.
> PredictionESP revamp

- README.md
It's just the new Perspective options
> pre61 update for ReadMe

- README.md
badges, sfx thing, feed replace and whatever else idk
> update readme to include new stuff (3.4.1pre72)

- StateFarmClient.js
module draws a line in the direction an enemy player is facing. Stops on collision with map.
> ShowLookDir, better name?

- StateFarmClient.js
- added clear code BL button
- duplicate check getCodeBlacklist 
-> code not added if already in the list
code blacklist more like code blacklust 🤤
> pre78 - minor code blacklist QOL

- StateFarmClient.js
and also remove puppy's console spam
> add Particle speed control

- StateFarmClient.js
-- swearing has never been *this* easy! --
-new c char
-special check (only lowercase but eh)
-format fix (NP++ moment)
> BypassFilter update v4

- StateFarmClient.js
-removed special chars: no special char replacement needed
> Remove unnecessary chatfilter chars (pre104)

- StateFarmClient.js
-prevent current special case: false positive with function "RotationX" (current update func name is nX)
> modifyControls regex fix

- StateFarmClient.js
-randomize your skybox!
-Rand interv (min): controls how often the skybox changes (in minutes)
> pre120: random skyboxes :3

- StateFarmClient.js
-remove broken skybox "sunrise"
-fix capitalization on the new modules to be consistent with the rest of the client
> pre121: minor skybox tweaks :3

- StateFarmClient.js
-added all tooltips
-minor module naming tweaks
> pre124: added missing tooltips :3

- StateFarmClient.js
changes:
- changed up crackedshell meta
- added crackedshell stuff at top of script
- moved from GM_* to GM.* - using GM_setValue now breaks, use GM.setValue instead
- renamed isCrackedShell to crackedShell
- added warning of depreciation when using crackedshell v1 (it won't work anyways because of meta changes)
crackedshell v2's code is being reviewed & uploaded to master now...
> pre128: crackedshell v2 support

- StateFarmClient.js
- getGameHistory button: displays the last 6 games as an alert and logs them into the console.
- deleteGameHistory button: clears the game history 
for puppy
> pre131: add game history

- StateFarmClient.js
come on, it's rainbow colors! How could you not want those in the client???
> pre 141: add Rainbow colors

- ingamebadges/badges.json
> add amzer to fbi

- StateFarmClient.js
i forgot to test this so i'm gonna let onlypuppy tell me if i broke it again #pre128
> pre155 - crackedshell fix (no more vardata prompt)

- StateFarmClient.js
> pre3: fix update history on new loading screen

- StateFarmClient.js
going to allow for 100x better debug
> pre8: give getstate.farm config information

- StateFarmClient.js
note that as you can immediately tell from the way i added it this is NOT designed to be something intertwined/inseparable into the client as much as it is something which can just be turned on and off. 
hint: `globalSS.verification.setVerified();`
> merge the verify system into main

- StateFarmClient.js
fixes issues with #227
reopened version of #228
we decided that account values being gone means there are no issues
> pre3: fix crackedshell, give safe values to getstate.farm

- StateFarmClient.js
`keyArr` is a constant and can't be modified, i should REALLY test my shit
> pre7: fix error, add `postMessage` value setting

- StateFarmClient.js
'cause these nights pass so much quicker than the days did
same clothes u aint ready for ur day shift
but u up, u need $$ for ur face lift
lust over love is your mindset
> pre28: sfc works but normal shell doesn't :100:

- StateFarmClient.js
- ingamebadges/badges.json
i think something else is broken i forgot ngl i'll figure it out after this class
> pre29: fix serversync + better logging

- StateFarmClient.js
- sfc can now be dual booted with infinite's megamod (fuck infinite, can code tho)
- there are now no longer duplicate keys
not a critical PR, just some general QOL for users
> fix a few issues

- README.md
- StateFarmClient.js
they sent me another DMCA to `js.getstate.farm` so we're on `archive.getstate.farm` now =D
> fix vardata
